/// <reference types="nativewind/types" />
/// <reference types="expo-router/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.
